import Head from "next/head";
import Avatar from "../components/Avatar";
import { MicrophoneIcon, ViewGridIcon } from "@heroicons/react/solid";
import { SearchIcon } from "@heroicons/react/outline";

import Image from "next/image";
import img from "../images/Ali.jpg";
// import Image from "next/image";
// import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <h1>Hello</h1> */}

      {/* header */}
      <header className="flex w-full p-5 justify-between text-sm text-gray-500">
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Images</p>
          {/* icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          {/* avatar */}
          <Avatar />
        </div>
      </header>
      {/* body */}
      <form>
        <Image
          src="https://www.google.co.uk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png"
          height={100}
          width={300}
        />
        <div className="flex w-full">
          <SearchIcon className="h-10 mr-3 text-gray-500" />
          {/* tailwind css does not work I set the background red and I dont see anything to see it */}
          <input
            type="text"
            className="bg-red-500 border-2 border-rose-600  focus:outline-none"
          />
          {/* when I set a h-5 it does not work  */}
          <MicrophoneIcon width={50} />
        </div>
      </form>

      {/* footer */}
    </div>
  );
}
